pipeline {
    agent {
        label('terraform-agent')
    }
    environment { 
        CC = 'clang'
    }
    stages {

        stage('Init') {
            steps {
                dir('terraform') {
                    dir('PRO'){
                        sh 'terraform init -upgrade'
                    }
                }
            }
        }

        stage('Build'){          
	        environment {
                CREDS = credentials('google-cloud-credentials')
            }
            steps{
                   
	            dir('terraform'){
	                dir('PRO'){
                        timeout(time: 10, unit: 'MINUTES') {
                        input message: 'Are you sure to deploy?', ok: 'Yes, deploying with terraform'
                            sh 'terraform -v'
                        }
                        sh 'cp \$CREDS application_default_credentials.json' 
		                sh 'terraform apply --auto-approve'
	                } 
		        }
	        }
	    }

    }
}

