pipeline {
    agent {
        label('terraform-agent')
    }
    stages {
        stage('Init') {
            steps {
                dir('terraform') {
                    sh 'terraform init -upgrade'
                }
            }
        }
	stage('Build'){
	    steps{
	        dir('terraform'){
		    sh 'terraform apply --auto-approve'
		}
	    }
	}
    }
}

