pipeline {
    agent {
        label('default')
    }
    stages {
        stage('Build') {
            steps {
                dir('terraform') {
                    sh 'terraform apply'
                }
            }
        }
    }
}

