pipeline {
    agent {
        label('terraform-agent')
    }
    stages {

        stage('Init') {
            steps {
                dir('terraform') {
                    sh 'terraform init -upgrade'
                }
            }
        }

        stage('Build'){          
	        steps{
	            dir('terraform'){
                    CREDS = credentials('google-cloud-credentials')
                    sh 'echo $CREDS'
		            sh 'terraform apply --auto-approve'
		        }
	        }
	    }

    }
}

